-- --------  << TF_3A_pabloguedes >>  ----------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 24/01/2023
-- Autor(es) ..............: Vitor Diniz Pagani Vieira Ribeiro - 180132385, Sara Campos - 170045269, Vitor Eduardo Kühl Rodrigues - 190118288, Pablo Christianno Silva Guedes - 200042416
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_3A_pabloguedes
--
-- PROJETO => 01 Base de Dados
--         => 15 Tabelas
-- 		   => 03 Papeis
--         => 05 Usuarios

-- Ultimas alterações:
-- 04/02/2023 => Criando novas tabelas de FOLHA_PONTO, INSUMO, CONTROLE_PONTO
-- 05/02/2023 => Adicionando Unique key na tabela TELEFONE e CLIENTE
-- 12/02/2023 => Removendo obrigatoriedade de cpf na tabela VENDA
-- ---------------------------------------------------------
CREATE DATABASE IF NOT EXISTS TF_3A_pabloguedes;

USE TF_3A_pabloguedes;

CREATE TABLE ENDERECO (
    idEndereco INT NOT NULL AUTO_INCREMENT,
    logradouro VARCHAR(50) NOT NULL,
    complemento VARCHAR(50) NOT NULL,
    numero INT NOT NULL,
    bairro VARCHAR(50) NOT NULL,
    cep INT NOT NULL,
    
    CONSTRAINT ENDERECO_PK PRIMARY KEY(idEndereco)
)ENGINE=InnoDB;

CREATE TABLE TELEFONE (
    idTelefone INT NOT NULL AUTO_INCREMENT,
    ddd INT NOT NULL,
    numeroTelefone INT NOT NULL,
    
    CONSTRAINT TELEFONE_PK PRIMARY KEY(idTelefone),
    CONSTRAINT TELEFONE_ddd_numeroTelefone_UK UNIQUE KEY(ddd, numeroTelefone)
)ENGINE=InnoDB;

CREATE TABLE PRODUTO (
    idProduto INT NOT NULL AUTO_INCREMENT,
    nomeProduto VARCHAR(30) NOT NULL,
    descricaoProduto VARCHAR(50) NOT NULL,
    valorUnitario DOUBLE NOT NULL,
    
    CONSTRAINT PRODUTO_PK PRIMARY KEY(idProduto)
)ENGINE=InnoDB;

CREATE TABLE FORNECEDOR (
    cnpjFornecedor BIGINT NOT NULL,
    nomeFornecedor VARCHAR(50) NOT NULL,
    idEndereco INT NOT NULL,
    idTelefone INT NOT NULL,
    
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY(cnpjFornecedor),
    CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY(idEndereco) REFERENCES ENDERECO(idEndereco) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FORNECEDOR_TELEFONE_FK FOREIGN KEY(idTelefone) REFERENCES TELEFONE(idTelefone) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE LOJA (
    cnpj BIGINT NOT NULL,
    nomeLoja VARCHAR(20) NOT NULL,
    idEndereco INT NOT NULL,
    idTelefone INT NOT NULL,
    
    CONSTRAINT LOJA_PK PRIMARY KEY(cnpj),
    CONSTRAINT LOJA_ENDERECO_FK FOREIGN KEY(idEndereco) REFERENCES ENDERECO(idEndereco),
    CONSTRAINT LOJA_TELEFONE_FK FOREIGN KEY(idTelefone) REFERENCES TELEFONE(idTelefone)
)ENGINE=InnoDB;

CREATE TABLE CLIENTE (
    cpfCliente BIGINT NOT NULL,
    nomeCompleto VARCHAR(50) NOT NULL,
    dataNascimento DATE NOT NULL,
    email VARCHAR(50) NOT NULL,
    idEndereco INT NOT NULL,
    idTelefone INT NOT NULL,
    
    CONSTRAINT CLIENTE_PK PRIMARY KEY(cpfCliente),
    CONSTRAINT CLIENTE_ENDERECO_FK FOREIGN KEY(idEndereco) REFERENCES ENDERECO(idEndereco),
    CONSTRAINT CLIENTE_TELEFONE_FK FOREIGN KEY(idTelefone) REFERENCES TELEFONE(idTelefone),
    CONSTRAINT PESSOA_email_UK UNIQUE KEY(email)
)ENGINE=InnoDB;

CREATE TABLE FUNCIONARIO (
    cpfFuncionario BIGINT NOT NULL,
    nomeCompleto VARCHAR(50) NOT NULL,
    dataContratacao DATE NOT NULL,
    idEndereco INT NOT NULL,
    dataNascimento DATE NOT NULL,
    idTelefone INT NOT NULL,
    cnpjLoja BIGINT NOT NULL,
    
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY(cpfFuncionario),
    CONSTRAINT FUNCIONARIO_ENDERECO_FK FOREIGN KEY(idEndereco) REFERENCES ENDERECO(idEndereco) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FUNCIONARIO_TELEFONE_FK FOREIGN KEY(idTelefone) REFERENCES TELEFONE(idTelefone) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FUNCIONARIO_LOJA_FK FOREIGN KEY(cnpjLoja) REFERENCES LOJA(cnpj) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE LOTE (
    idLote INT NOT NULL AUTO_INCREMENT,
    dataEntrada DATE NOT NULL,
    qtdeRecebida INT NOT NULL,
    custo DOUBLE NOT NULL,
    cnpjFornecedor BIGINT NOT NULL,
    cpfFuncionario BIGINT NOT NULL,
    cnpjLoja BIGINT NOT NULL,
    
    CONSTRAINT LOTE_PK PRIMARY KEY(idLote),
    CONSTRAINT LOTE_FORNECEDOR_FK FOREIGN KEY(cnpjFornecedor) REFERENCES FORNECEDOR(cnpjFornecedor) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT LOTE_FUNCIONARIO_FK FOREIGN KEY(cpfFuncionario) REFERENCES FUNCIONARIO(cpfFuncionario) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT LOTE_LOJA_FK FOREIGN KEY(cnpjLoja) REFERENCES LOJA(cnpj) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE INSUMO (
    idInsumo INT NOT NULL AUTO_INCREMENT,
    nomeInsumo VARCHAR(20) NOT NULL,
    qtdeEstoque INT NOT NULL,
    dataValidade DATE NOT NULL,
    idLote INT NOT NULL,
    
    CONSTRAINT INSUMO_PK PRIMARY KEY(idInsumo),
    CONSTRAINT INSUMO_LOTE_FK FOREIGN KEY(idLote) REFERENCES LOTE(idLote) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE CONTROLE_FERIAS (
    idControle INT NOT NULL AUTO_INCREMENT,
    dataInicio DATE NOT NULL,
    dataFim DATE NOT NULL,
    cpfFuncionario BIGINT NOT NULL,
    
    CONSTRAINT CONTROLE_FERIAS_PK PRIMARY KEY (idControle),
    CONSTRAINT CONTROLE_FERIAS_FUNCIONARIO_FK FOREIGN KEY(cpfFuncionario) REFERENCES FUNCIONARIO(cpfFuncionario) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE FOLHA_PONTO (
    idFolha INT NOT NULL AUTO_INCREMENT,
    dataFolha DATE NOT NULL,
    horaSaida TIME NOT NULL,
    horaEntrada TIME NOT NULL,
    cpfFuncionario BIGINT NOT NULL,
    
    CONSTRAINT FOLHA_PONTO_PK PRIMARY KEY(idFolha),
    CONSTRAINT FOLHA_PONTO_FUNCIONARIO_FK FOREIGN KEY(cpfFuncionario) REFERENCES FUNCIONARIO(cpfFuncionario) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE VENDA (
    idVenda INT NOT NULL AUTO_INCREMENT,
    senha INT NOT NULL,
    dataVenda DATE NOT NULL,
    formaPagamento ENUM('DB', 'CR', 'D') NOT NULL,
    horaVenda TIME NOT NULL,
    notaFiscal VARCHAR(44) NOT NULL,
    desconto DOUBLE NOT NULL,
    cnpjLoja BIGINT NOT NULL,
    cpfCliente BIGINT,
    cpfFuncionario BIGINT NOT NULL,
    
    CONSTRAINT VENDA_PK PRIMARY KEY(idVenda),
    CONSTRAINT VENDA_LOJA_FK FOREIGN KEY(cnpjLoja) REFERENCES LOJA(cnpj) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT VENDA_CLIENTE_FK FOREIGN KEY(cpfCliente) REFERENCES CLIENTE(cpfCliente) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT VENDA_FUNCIONARIO_FK FOREIGN KEY(cpfFuncionario) REFERENCES FUNCIONARIO(cpfFuncionario) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE DEPENDENTE (
    idDependente INT NOT NULL AUTO_INCREMENT,
    nomeDependente VARCHAR(50) NOT NULL,
    sexo ENUM('M', 'F') NOT NULL,
    dataNascimento DATE NOT NULL,
    parentesco VARCHAR(20) NOT NULL,
    cpfFuncionario BIGINT NOT NULL,
    
    CONSTRAINT DEPENDENTE_PK PRIMARY KEY(idDependente),
    CONSTRAINT DEPENDENTE_FUNCIONARIO_FK FOREIGN KEY(cpfFuncionario) REFERENCES FUNCIONARIO(cpfFuncionario) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE possui (
    idProduto INT NOT NULL,
    idVenda INT NOT NULL,
    
    CONSTRAINT possui_PRODUTO_FK FOREIGN KEY(idProduto) REFERENCES PRODUTO(idProduto) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT possui_VENDA_FK FOREIGN KEY(idVenda) REFERENCES VENDA(idVenda) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

CREATE TABLE usa (
    idProduto INT NOT NULL,
    idInsumo INT NOT NULL,
    
    CONSTRAINT usa_PRODUTO_FK FOREIGN KEY(idProduto) REFERENCES PRODUTO(idProduto) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT usa_INSUMO_FK FOREIGN KEY(idInsumo) REFERENCES INSUMO(idInsumo) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB;

